spring:
  application:
    name: spring-cloud-api-gateway-service

  cloud:
    gateway:
      routes:
        - id: stock-enquiry
          uri: http://techefx-product-enquiry-service:8700/
          predicates:
            - Path=/product-enquiry/**

server:
  port: ${port:8900}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
